services:
  - type: web
    name: web-studio
    env: node
    rootDir: apps/web
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/news
    envVars:
      - key: NODE_ENV
        value: production
